arb/const_khinchin.c, arb/exp_sum_bs_powtab.c
(for warnings reported by clang)
What a pity; now I missed #42...
=> fix two compiler warnings

acb.h, arb.h, doc/source/acb.rst, doc/source/arb.rst
A few functions for ease of use.
=> Add various set functions

acb_mat.h, acb_mat/eq.c, acb_mat/ne.c, acb_mat/set_arb_mat.c, acb_mat/set_round_arb_mat.c, arb_mat.h, arb_mat/eq.c, arb_mat/ne.c, doc/source/acb_mat.rst, doc/source/arb_mat.rst
If the functions look fine to you, I can add documentation.
=> Add arb_mat_eq/ne (and more)!

Makefile.in
This fix is required for Nemo to use Arb correctly.
=> Support LDFLAGS.

Makefile.in
After some testing we have found that this is the good order for things when linking.
=> Correct order for linker line.

acb_mat/test/t-mul.c
A second attempt to increase test coverage of `acb_mat_mul`.
=> TST: more thorough testing of complex matrix multiplication

acb_mat.h, acb_mat/test/t-trace.c, acb_mat/trace.c, arb_mat.h, arb_mat/test/t-trace.c, arb_mat/trace.c, doc/source/acb_mat.rst, doc/source/arb_mat.rst
Add `arb_mat_trace` and `acb_mat_trace`. Much of the code is duplicated.
=> ENH: add trace

Makefile.in, acb_mat/exp.c, arb_mat/exp.c, fmpz_mat_extras.h, fmpz_mat_extras/test/t-transitive_closure.c, fmpz_mat_extras/transitive_closure.c
=> MAINT: move transitive_closure to a new fmpz_mat_extras module

acb_mat/test/t-exp.c, arb_mat/test/t-exp.c
addresses https://github.com/fredrik-johansson/arb/pull/97#issuecomment-189050762
=> TST: increase matrix exp test coverage

acb_mat/exp.c, arb_mat/exp.c
This code churn uses `bool_mat` for the 'structural' parts of matrix exp. It shouldn't change the behavior. In particular, it is not yet trying to be clever about nilpotent matrices or about non-nilpotent matrices for which some entries have only a finite number of nonzero terms in the matrix power series.
=> MAINT: use bool_mat for structure detection in matrix exp

acb_mat/exp.c, arb_mat/exp.c
This uses a 'structural' nilpotency degree bound that depends only on the sparsity structure of the matrix.
```
exp(
[0, 1, -1]
[0, 0, 2]
[0, 0, 0]
)
before PR:
[1 +/- 0, 1 +/- 9.3326e-17, 0 +/- 2.2457e-16]
[0 +/- 0, 1 +/- 0, 2 +/- 9.3326e-17]
[0 +/- 0, 0 +/- 0, 1 +/- 0]
after PR:
[1 +/- 0, 1 +/- 0, 0 +/- 0]
[0 +/- 0, 1 +/- 0, 2 +/- 0]
[0 +/- 0, 0 +/- 0, 1 +/- 0]
```
```
exp(
[0 +/- 0, 7.88860905221012e-31 +/- 0, 0 +/- 0]
[0 +/- 0, 0 +/- 0, 1.26765060022823e+30 +/- 0]
[0 +/- 0, 0 +/- 0, 0 +/- 0])
before PR:
[1 +/- 0, 7.88860905221012e-31 +/- 2.0842e+13, 0.5 +/- 1.321e+43]
[0 +/- 0, 1 +/- 0, 1.26765060022823e+30 +/- 2.0842e+13]
[0 +/- 0, 0 +/- 0, 1 +/- 0]
after PR:
[1 +/- 0, 7.88860905221012e-31 +/- 0, 0.5 +/- 0]
[0 +/- 0, 1 +/- 0, 1.26765060022823e+30 +/- 0]
[0 +/- 0, 0 +/- 0, 1 +/- 0] …
```
=> ENH: use nilpotency degree to improve matrix exp error bounds

acb_mat/exp.c, arb_mat/exp.c
Improves entrywise error bounds for the matrix exponential. This method detects all entries for which a matrix Taylor series can be safely truncated to N terms given the sparsity structure of the matrix.
```
exp(
[1, 1, 0, 0]
[0, 0, 1, -1]
[0, 0, 0, 2]
[0, 0, 0, 0]
)
before PR:
[2.71828182786703 +/- 9.315e-10, 1.71828182833269 +/- 4.6574e-10,
0.718281828332692 +/- 2.3286e-10, -0.281718171434477 +/- 1.1644e-10]
[0 +/- 0, 1 +/- 0, 1 +/- 9.3326e-17, 0 +/- 2.2457e-16]
[0 +/- 0, 0 +/- 0, 1 +/- 0, 2 +/- 9.3326e-17]
[0 +/- 0, 0 +/- 0, 0 +/- 0, 1 +/- 0]
after PR:
[2.71828182786703 +/- 9.315e-10, 1.71828182833269 +/- 4.6574e-10,
0.718281828332692 +/- 2.3285e-10, -0.281718171434477 +/- 1.1644e-10]
[0 +/- 0, 1 +/- 0, 1 +/- 0, 0 +/- 0]
[0 +/- 0, 0 +/- 0, 1 +/- 0, 2 +/- 0]
[0 +/- 0, 0 +/- 0, 0 +/- 0, …
```
=> ENH: better entrywise truncation errors for matrix powers

arb/contains.c, arb/contains_arf.c, arb/overlaps.c, arb/richcmp.c
Try to replace some magic numbers with the appropriate name. I'm not sure if this is correct. The motivation was to help look into how `arb_intersection` might be implemented.
=> MAINT: 30 -> MAG_BITS

acb_hypgeom.h, acb_hypgeom/gamma_lower.c, acb_hypgeom/test/t-gamma_lower.c, acb_hypgeom/test/t-gamma_upper.c, doc/source/acb_hypgeom.rst
This is mostly copied from the upper gamma implementation. I don't know about a couple of the edge cases that were specially handled by the upper gamma code, so I've left some 'todo' comments. Maybe it's related to branch cuts or something, I'm not sure.
It partially addresses https://github.com/fredrik-johansson/arb/issues/36.
=> ENH: add lower gamma

acb_hypgeom.h, acb_hypgeom/gamma_upper_series.c, acb_hypgeom/test/t-gamma_upper_series.c, acb_poly.h, doc/source/acb_hypgeom.rst, doc/source/acb_poly.rst
part of https://github.com/fredrik-johansson/arb/issues/36
=> MAINT: move upper incomplete gamma series from acb_poly to acb_hypgeom

arb_poly.h, arb_poly/test/t-root_bound_fujiwara.c, doc/source/arb_poly.rst
Adding arb_poly counterparts https://github.com/fredrik-johansson/arb/pull/141#issuecomment-215368465.
=> ENH: arb poly scalar mul and div

arb_mat/exp.c
closes https://github.com/fredrik-johansson/arb/issues/147
=> MAINT: improve entrywise relative accuracy of exponentials of matrices with small norms

.travis.yml
Fixes https://github.com/fredrik-johansson/arb/issues/193
=> Fix travis-ci error

acb/acos.c, acb/acosh.c
=> return exact zero where possible: acos, acosh

acb_dirichlet/isolate_hardy_z_zero.c
zeta_zero is twice as fast for me now for large n (8637740722917 and 8637740722918).
=> tighten an interval, giving a speedup for large n

acb_dirichlet/isolate_hardy_z_zero.c
This PR makes more efficient use of evaluated nodes to sometimes speed up isolation of a zero of the Hardy Z-function. For example the time required to isolate the 8637740722917th and 8637740722918th zeros is reduced by ~25%.
When n is large, the mpmath algorithm immediately starts looking for `2*B` consecutive good blocks above the predicted zero location and for `2*B` consecutive good blocks below the predicted zero location, where `B` is a Turing method bound. An advantage of this strategy is that N(t) is known with certainty at the Gram point in the middle of each stretch of consecutive good blocks. This certainty simplifies the algorithm.
But it's not always necessary to have a `2*B` stretch to learn N(t). If you can find k sign changes in a region of k Gram intervals then if this …
=> a more sophisticated application of the turing method

acb_dirichlet.h, acb_dirichlet/isolate_hardy_z_zero.c, acb_dirichlet/test/t-zeta_nzeros.c, doc/source/acb_dirichlet.rst
This implementation of N(t) reuses most of the zeta zero isolation code, some of which has been refactored.
=> add zeta_nzeros

acb_dirichlet/isolate_hardy_z_zero.c
This PR speeds up nzeros by 2x for large inexact arb t, when the t interval is small enough relative to the spacing of the nontrivial zeta zeros near height t.
It doesn't usually speed up nzeros at intervals surrounding Gram points, but it would be possible to add a more efficient special function to get nzeros at Gram points specifically.
=> nzeros speedup

acb_dirichlet.h, acb_dirichlet/platt_c_bound.c, acb_dirichlet/platt_i_bound.c, acb_dirichlet/platt_ws_interpolation.c, acb_dirichlet/test/t-platt_ws_interpolation.c, doc/source/acb_dirichlet.rst, doc/source/credits.rst
This PR implements the Whittaker-Shannon interpolation component of Platt's method of isolating zeta zeros. Here's an example plot of the interpolation (with error bounds):
=> platt whittaker shannon interpolation

acb_dirichlet/platt_ws_interpolation.c
Implements the suggestion by @simonpuchert to close https://github.com/fredrik-johansson/arb/issues/284.
=> use trig identity to speed up WS interpolation

acb_dirichlet.h, acb_dirichlet/platt_local_hardy_z_zeros.c, acb_dirichlet/platt_ws_interpolation.c, acb_dirichlet/test/t-platt_ws_interpolation.c, arb_poly.h, arb_poly/sinc_pi_series.c, arb_poly/test/t-sinc_pi_series.c, doc/source/acb_dirichlet.rst, doc/source/arb_poly.rst
closes https://github.com/fredrik-johansson/arb/issues/285
=> interpolation derivative for zeros refinement under limited precision

acb_dirichlet.h, acb_dirichlet/platt_local_hardy_z_zeros.c, doc/source/acb_dirichlet.rst
Heuristically picks ten tuning parameter values for Platt's method of finding zeros of the Hardy Z function.
=> heuristic tuning parameters for platt hardy z zeros

acb_dirichlet/stieltjes.c
see #278, __ are reserved according to the C99 standard.
=> Fix clash of __hypot

CMakeLists.txt, appveyor.yml, arb/test/t-dump_file.c, doc/source/setup.rst
`dump-file` tests fail. cc @saraedum 
https://ci.appveyor.com/project/isuruf/arb/builds/32420989
=> Windows CI

acb_hypgeom/gamma_upper.c, acb_hypgeom/u_asymp.c
This pull request improves the implementation of `acb_hypgeom_gamma_upper` by no longer dispatching to `acb_hypgeom_gamma_upper_asymp` under certain conditions when doing so can be predetermined to give an uninformative result (nan +/- inf). The improvement is particularly noticeable when `s` is large compared to `z` and to the number of bits of working precision.
The shaded region of this [figure](https://dlmf.nist.gov/13.7#F1) shows where `z` is too close to the origin for the asymptotic expansion to work, and the scale of that region depends on `s`. The old code uses the asymptotic expansion when `z` is outside a disk whose radius is proportional to the working precision, without taking `s` into account. The new code adds a condition requiring `z` to also be outside of the shaded …
=> avoid asymptotic expansion for the upper incomplete gamma function under some conditions

.github/workflows/ci-sage.yml
see comments in the new file `.github/workflows/ci-sage.yml`. Preview of the CI run: https://github.com/mkoeppe/arb/runs/839286291
=> Add portability testing and continuous integration using Sage

acb_mat/eig_simple_rump.c, acb_mat/test/t-eig_simple.c
Closes https://github.com/fredrik-johansson/arb/issues/329.
=> fix typo R -> R2

doc/source/acb.rst
closes https://github.com/fredrik-johansson/arb/issues/319
=> fix a typo in docs

acb_hypgeom/bessel_j.c, acb_hypgeom/bessel_y.c, arb/sinc_pi.c, arb/test/t-sinc_pi.c, arb_hypgeom/test/t-bessel_j.c, arb_hypgeom/test/t-bessel_y.c
handles infinity for more arb functions related to https://github.com/fredrik-johansson/arb/issues/306
=> special values for bessel j and y and for sinc_pi

Makefile.in, Makefile.subdirs, acb_dft/profile/p-convol.c, acb_dft/profile/p-dft.c, acb_dirichlet/profile/p-gauss.c, acb_dirichlet/profile/p-jacobi.c, acb_dirichlet/profile/p-vec.c, dirichlet/profile/p-conrey.c, dlog/profile/p-precomp.c, dlog/profile/p-vec.c
The command `make profile` used to give an error, but now it works for me. I think this code fell through the cracks when arb split from flint.
=> fix make profile

acb_dirichlet/platt_multieval.c, acb_dirichlet/platt_multieval_threaded.c
With this PR the multi-threading memory overhead of `acb_dirichlet_platt_multieval` is negligible.
=> use less memory for multi-threaded acb_dirichlet_platt_multieval

acb_dirichlet/platt_multieval.c, acb_dirichlet/platt_multieval_threaded.c
This PR is in response to https://github.com/fredrik-johansson/arb/issues/335#issuecomment-699024877 lured by the prospect of saving 130000 seconds. In my tests it increases efficiency like 5% or 10%. If you are running something for a day on 32 cores then I guess it could technically save 130000 cpu-seconds.
=> in platt multieval : slightly faster j loop

acb_dirichlet/platt_multieval.c
I see about 25% speedup. It includes a custom `acb_dot_arb` function that treats a length n vector of acb structs like a length 2*n vector of arb structs. I saw this pattern in acb.h so I guess it's OK.
=> in platt multieval break the j loop into blocks and use dot product

CMakeLists.txt
Same thing as https://github.com/wbhart/flint2/pull/875 but for arb.
=> CMakeLists.txt: support standard GNU installation directories

acb_elliptic.h, acb_elliptic/p_prime.c, acb_elliptic/test/t-p_p_prime.c, doc/source/acb_elliptic.rst
I guess this is for when you want p' but not p. ¯\_(ツ)_/¯
=> add acb_elliptic_p_prime

appveyor.yml
Fixes https://github.com/fredrik-johansson/arb/issues/397
=> update conda location in appveyor

doc/source/acb.rst, doc/source/arb_hypgeom.rst
This fixes two minor errors in the documentation I found when preparing https://github.com/kalmarek/Arblib.jl/pull/146.
=> Minor fixes to documentation

arb/addmul.c, arb/fma.c, arb/mul.c, arb/submul.c, arb/test/t-addmul.c, arb/test/t-mul.c, arb/test/t-pos_times_posinf.c, arb/test/t-submul.c
This addresses github issue #408.
=> Positive * pos_inf should be pos_inf, not 0 +- inf. Same for other combinations of signs.

arb_fpwrap/fpwrap.c, arb_fpwrap/test/t-fpwrap.c, doc/source/arb_fpwrap.rst
This is only a proposal. I haven't tested this.
=> add lerch_phi to fpwrap

doc/source/fmpzi.rst, fmpzi.h, fmpzi/gcd_shortest.c, fmpzi/test/t-gcd_shortest.c
=> add fmpzi_gcd_shortest

fmpzi/gcd_shortest.c, fmpzi/profile/p-gcd.c
Does some easy mod reductions to reduce the intermediate swell in the hnf.
=> smarter hnf in fmpzi_gcd_shortest
