arb/test/t-set_str.c
MinGW uses MSVCRT.DLL atof(s) which is not ISO-C compliant. It returns
atof("inf")=0 and the test fails. Seems strtod(s, NULL) works correctly,
with the same intended functionality, and the test passes.
=> using strtod(...) instead atof(...) in arb/test/t-set_str.c to make it MinGW compatible

Makefile.in
It seems the order of LDFLAGS and LIBS2 may be critical.
=> Put LDFLAGS and LIBS2 in same order as in Flint.

acb_modular/hilbert_class_poly.c
closes https://github.com/fredrik-johansson/arb/issues/59
=> MAINT: use n_gcd_full for FLINT 2.4 compatibility

acb_mat.h, acb_mat/exp.c, acb_mat/pow_ui.c, acb_mat/sqr.c, acb_mat/test/t-sqr.c, arb_mat.h, arb_mat/exp.c, arb_mat/sqr.c, arb_mat/sqr_classical.c, arb_mat/test/t-sqr.c, doc/source/acb_mat.rst, doc/source/arb_mat.rst
Save a few multiplications when squaring a matrix. Best for high precision 2x2 matrices. Maybe slightly slower for low-precision large-dimension matrices (i.e. the case where you would want to use BLAS instead).
sqr/mul timing ratios:
|  | n=2 | n=4 | n=10 | n=100 | 
|---|---|---|----|-----| 
| prec=32 | 0.730 | 0.883 | 0.985 | 1.008 | 
| prec=64 | 0.655 | 0.814 | 0.953 | 1.001 | 
| prec=1024 | 0.688 | 0.771 | 0.916 | 0.993 | 
| prec=4096 | 0.555 | 0.738 | 0.871 | 0.986 |
=> ENH: arb_mat_sqr

arb.h
found by compiler flag `-Wredundant-decls`
=> MAINT: redundant function declarations

arb.h, arb/sinc.c, arb/test/t-sinc.c, doc/source/arb.rst
Here's an implementation of `sinc` based on my interpretation of the comments in https://github.com/fredrik-johansson/arb/issues/70#issuecomment-161121373.
It picks among four different evaluations of `sinc` depending on the midpoint and radius of x.
Here's a diagram showing that different methods work better in different regions (midpoint increases top to bottom, radius increases left to right).
=> ENH: add sinc

arb_poly.h
This is a small nitpick to get rid of a `-Wsign-compare` compiler warning. I'm not completely sure it's correct, but I think it is.
```
/usr/local/include/flint/flint.h:237:42: warning: signed and unsigned type in co
nditional expression [-Wsign-compare]
#define FLINT_MIN(x, y) ((x) > (y) ? (y) : (x))
^
../arb/arb_poly.h:663:12: note: in expansion of macro ‘FLINT_MIN’
return FLINT_MIN(lo, trunc);
^
```
=> MAINT: explicit cast to avoid comparing signed vs. unsigned

arf.h
Fix #77: the temporary variable names `__x0` and similar conflict with temporary variables used in FLINT macros.
=> Use variable names which do not conflict with FLINT

acb_mat/exp.c, acb_mat/test/t-exp.c, arb_mat/exp.c, arb_mat/test/t-exp.c, doc/source/arb_mat.rst
This PR improves `exp` bounds for matrices that have a structure that is unaffected by taking matrix powers. Examples include diagonal, triangular, or block matrices, possibly under permutation.  This improvement is achieved by detecting matrix entries that are structurally determined and not adding Taylor series truncation errors to these entries. There shouldn't be too much overhead for matrices without this structure.
For structured matrices the `exp` calculation not only has improved bounds, but is also computed faster. The reason for the speedup is that intermediate matrices in the squaring step of 'scaling and squaring' used to have a nontrivial error radius for every matrix entry, whereas after this PR some of these entries have zero error radius.
No new tests have been added, and …
=> ENH: improved structured matrix exp bounds

arb_mat.h, arb_mat/adjacency.c, arb_mat/count_is_zero.c, arb_mat/entrywise_is_zero.c, arb_mat/entrywise_not_is_zero.c, arb_mat/exp.c, doc/source/arb_mat.rst
This PR only adds docs and reorganizes code, and it should not affect the behavior of existing public functions.
It adds the new file `arb_mat/adjacency.c` containing `_arb_mat_entrywise_nonzero_round_up` and `_arb_mat_count_nonzero_round_up` which are wrapped in the header file by `arb_mat_adjacency` and `arb_mat_count_nonzero`. This breaks the existing `arb_mat` convention of 1:1 correspondence between public function names and .c file names, so if that convention is important then this PR should not be merged as-is.
This PR has not included analogous changes to `acb_mat`.
=> MAINT: document sparsity-related arb_mat functions and move them to a separate file

acb_mat.h, acb_mat/mul_entrywise.c, acb_mat/test/t-mul_entrywise.c, arb_mat.h, arb_mat/mul_entrywise.c, arb_mat/test/t-mul_entrywise.c, doc/source/acb_mat.rst, doc/source/arb_mat.rst
Includes docs and tests. Closes https://github.com/fredrik-johansson/arb/issues/69. Test execution times are under control because test settings are copied from matrix multiplication, and matrix products are slower than entrywise products.
=> ENH: mul_entrywise

acb_mat.h, acb_mat/det.c, acb_mat/exp.c, acb_mat/lu.c, acb_mat/sqr.c, acb_mat/trace.c, acb_mat/transpose.c, arb_mat.h, arb_mat/det.c, arb_mat/exp.c, arb_mat/lu.c, arb_mat/sqr_classical.c, arb_mat/trace.c, arb_mat/transpose.c, doc/source/acb_mat.rst, doc/source/arb_mat.rst
These functions have the same meaning as in `fmpz_mat`. Docs are included. This PR also includes some small related (and some unrelated...) code tweaks that should not change any behavior.
=> MAINT: is_square and is_empty for arb_mat and acb_mat

bool_mat/test/t-complement.c
I wasn't clearing a bool_mat in one of the unit tests.
The valgrind tests could be streamlined to check a whole module at once for error/leaks. For this PR I am doing this by running `$ make valgrind MOD=bool_mat` and then inspecting `cat build/bool_mat/test/t-*.valgrind` visually for anything that looks like an error or leak, but it could be automated. It would also be nice if the number of iterations were reduced by maybe 10x when running valgrind, but I know that arb doesn't have that iteration control yet.
=> MAINT: fix mem leak in bool_mat complement involution test

arb.h, arb/intersection.c, arb/test/t-intersection.c, doc/source/arb.rst
Sets an output value to an interval containing an intersection, and has the same integer return value as `arb_overlaps()`.
Closes https://github.com/fredrik-johansson/arb/issues/114.
This doesn't include an `acb` implementation yet. I guess that should be added after the `arb` version is reviewed and before it is merged.
=> ENH: arb_intersection

arb.h, doc/source/arb.rst
related to https://github.com/fredrik-johansson/arb/issues/71
The `_arb_vec_get_mag` function also seems questionable to me. I would expect a function with that name to compute the magnitude of the vector. But it actually computes the vector infinity norm, which I'd expect to be named something like `_arb_vec_get_inf_norm`.
=> MAINT: remove _arb_vec_norm which did not actually compute a norm

arb.h, arb/max.c, arb/min.c, arb/test/t-max.c, arb/test/t-min.c, doc/source/arb.rst
Includes tests and docs. The implementation and tests follow `arb_union` and the docs follow those of the analogous `arf` functions.
=> ENH: arb min and max

acb_mat.h, acb_mat/bound_fro_norm.c, acb_mat/test/t-trace.c, arb_mat.h, arb_mat/bound_fro_norm.c, arb_mat/test/t-trace.c, doc/source/acb_mat.rst, doc/source/arb_mat.rst
Includes docs, and an identity involving this norm and the matrix trace has been added to the trace tests. It's implemented for real and complex matrices. A variant that computes an `arb_t` interval instead of a `mag_t` upper bound could be useful too, but that is not implemented here.
=> ENH: frobenius norm

acb.h, arb.h, configure, doc/source/acb.rst, doc/source/arb.rst
This fixes issue #135, although not an elegant fix.  
Add function arb_sqr requested in issue #113  as well as acb_sqr and documentation.
=> Build Extension Module Examples, add arb_sqr and acb_sqr

acb_hypgeom.h, acb_hypgeom/gamma_lower_series.c, acb_hypgeom/test/t-gamma_lower_series.c, doc/source/acb_hypgeom.rst
This is mostly copypasted from gamma upper series. For regularized=0 or regularized=1, higher order coefficients in the lower series should be negatives of the corresponding coefficients in the upper series. Regularization option 2 is defined slightly differently for lower vs. upper gamma, by a factor of Gamma(s).
=> ENH: add incomplete gamma lower series

doc/source/acb.rst
It's a matter of opinion, but I think that the documentation for acb_is_zero, acb_is_one, acb_is_finite, and acb_is_exact should be in section "Precision and Comparisons" and not in the section "Basic Manipulations".  If you disagree, I'll close this pull request.
=> Move some existing documentation for acb types

.travis.yml
Fixes #168 
Issue in OSX 10.11 is not fixed here, but uses OSX 10.10 to test on travis.
=> Fix OS X on travis-ci

.travis.yml
executables created in make check were looking for libarb in the
installation directory but libarb may not be installed yet.
As a workaround, arb is installed in travis-ci before make check
is run
=> Fix osx link issue in travis-ci

arf.h, bool_mat.h, dlog.h, fmpr.h, fmpz_extras.h, mag.h
Since there is no global header file (or I could not find it), these checks are scattered all over the place.
=> Change abort to flint_abort only if flint > 2.5.2

dirichlet/group_init.c, dirichlet/test/t-properties.c
The bug was caused by overflows in the test file.
This commit also makes lift_generators stronger (there was a possible overflow in case of a large generator).
=> fix test for 32 bits

Makefile.in
Currently `Makefile.in` installs static libraries in `$(DESTDIR)/$(PREFIX)/lib` instead of `$(DESTDIR)/$(PREFIX)/$(LIBDIR)` as the dynamic one. This can have funny consequence since `$(DESTDIR)/$(PREFIX)/$(LIBDIR)` is created by the install target but `$(DESTDIR)/$(PREFIX)/lib` isn't. `/usr/lib` usually exist on unix but when `DESTDIR` is set all your bets are off. As seen in https://github.com/cschwan/sage-on-gentoo/issues/471 the side effects are interesting.
=> install static library in LIBDIR instead of lib

acb_dirichlet/xi.c, acb_dirichlet/zeta.c
Applying the functional equation to xi and zeta when s includes zero and has its midpoint in the left half plane causes infinite error bounds.
=> xi and zeta near zero

acb_dirichlet.h, acb_dirichlet/backlund_s_bound.c, acb_dirichlet/test/t-backlund_s_bound.c, doc/source/acb_dirichlet.rst, doc/source/credits.rst
Add an upper bound for `|S(t)|` when `t >= 0`. It's related to the irregularity of spacing of nontrivial zeros of the Riemann zeta function.
=> add backlund_s_bound

acb_dirichlet.h, acb_dirichlet/gram_point.c, acb_dirichlet/test/t-gram_point.c, acb_dirichlet/test/t-turing_method_bound.c, acb_dirichlet/turing_method_bound.c, doc/source/acb_dirichlet.rst, doc/source/credits.rst
Add an integer bound related to Turing's method, like sure_number_block in zetazeros.py in mpmath. gram_point is generalized following Brent 1979 to allow n=-1. Tests and docs are added/updated.
=> add turing_method_bound

acb_dirichlet.h, acb_dirichlet/backlund_s_gram.c, acb_dirichlet/isolate_hardy_z_zero.c, acb_dirichlet/test/t-backlund_s_gram.c, acb_dirichlet/test/t-zeta_nzeros.c, acb_dirichlet/test/t-zeta_nzeros_gram.c, doc/source/acb_dirichlet.rst
These are twice as fast and return integers rather than arb intervals. Also the code is simpler and can be used for testing against the more general case.
=> Add functions specific to Gram points

acb_dirichlet/platt_c_bound.c, acb_dirichlet/platt_lemma_A11.c, acb_dirichlet/platt_lemma_A5.c, acb_dirichlet/platt_ws_interpolation.c, acb_dirichlet/test/t-platt_multieval.c
This PR adds regression tests for each of the eight lemma bounds that are involved in the error calculations for the Platt multieval function. To help prevent or detect typos in the implementations, the values hardcoded in the tests were computed with PARI/GP code independent from arb. The tests do not verify the inequalities of the bounds themselves so typos in the primary literature wouldn't be detected.
The plan for the next PR is to add a low level `zeta_zeros`-like function that takes about a dozen tuning parameters and that isolates zeros within a single fft region, maybe on the order of a thousand zeros. If the tuning parameters are well chosen then it should be significantly faster than the existing zeta zeros implementation but if the tuning parameters are poorly chosen then the …
=> tests for platt lemma bounds

acb_dirichlet.h, acb_dirichlet/isolate_hardy_z_zero.c, acb_dirichlet/platt_local_hardy_z_zeros.c, acb_dirichlet/platt_ws_interpolation.c, acb_dirichlet/test/t-platt_local_hardy_z_zeros.c, doc/source/acb_dirichlet.rst
This PR implements the first part of the plan outlined in https://github.com/fredrik-johansson/arb/pull/281 (a low level `zeta_zeros`-like function that takes about a dozen tuning parameters and that isolates zeros within a single fft region).
To compare speed, I checked isolation only (not refinement) of 8000 consecutive zeros starting at n=103800788359 (the last zero in Platt's database). The old way took about half an hour and the new way took one minute, so there is some speed improvement. The parameter values were T=30610047000, A=8, B=4096, prec=300, sigma_grid=1601, K=44, J=103000, h=176431/2048, H=677/512, sigma_interp=25, Ns_max=300.
=> platt local zeros

.gitignore
arb does not use automake but a project might pull in arb as a submodule
and build parts of it with automake
=> gitignore automake/libtool artifacts

CMakeLists.txt
This makes the cmake script more portable. Fixes #296 .
=> Remove NO_DEFAULT_PATH from CMakeLists.txt; fixes #296

doc/source/arb_hypgeom.rst
Trying to do some automatic parsing of the documentation in relation to [Arblib.jl](https://github.com/kalmarek/Arblib.jl) I ran into this parsing error.
=> fix doc typo

acb.h, acb/fprintn.c, arb.h, arb/get_lbound_arf.c, arb/get_ubound_arf.c, doc/source/arb.rst, partitions/hrr_sum_arb.c
In general arb uses `slong` for 64 bits signed integers, in a few places `long` was used instead. I believe all of these cases are just typos and this pull request fixes those. There seems to be no other occurrences as determined by `grep -R " long"` (notice the space before `long`).
=> Remove long

examples/integrals.c
While looking at integrals of gamma-related functions with the hope of improving the incomplete gamma function implementation for zeta zeros parameter tuning I noticed this constant on Wikipedia so I've tried adding it as an integral example. Later I saw on its oeis entry that you've already written this code lol, but I thought I'd submit this pr anyway.
=> add fransen robinson constant as an integral example

acb_dirichlet/platt_local_hardy_z_zeros.c, doc/source/acb_dirichlet.rst
Fixes a mistake in the implementation of Platt's algorithm for finding multiple zeta zeros at once. The bug meant that the code was checking a regularity condition that was different than the intended condition. I don't know about the practical impact. It also caused the code to unnecessarily abort in certain circumstances when no results could be found.
=> fix a zeta zeros issue

acb_dirichlet/platt_c_bound.c, acb_dirichlet/platt_lemma_A11.c, acb_dirichlet/platt_lemma_A5.c, acb_dirichlet/platt_ws_interpolation.c, acb_hypgeom/gamma_upper.c, acb_hypgeom/test/t-gamma_upper.c
When s and z are nonnegative real, the asymptotic expansion is used when `(z-c)^8 > (a*s)^8 + (b*prec)^8` where `a=1.029287542, b=0.3319411658, c=2.391097143`. For reference the `acb_hypgeom_u_use_asymp` condition has `a=0, b=0.69314718055994530942, c=0` in this notation.
Closes https://github.com/fredrik-johansson/arb/issues/276.
Closes https://github.com/fredrik-johansson/arb/issues/166.
The [magic constants](https://en.wikipedia.org/wiki/Magic_number_(programming)) were found by locating the best transition point for each point in the grid prec=16..400 s=0.5..200.5 then contour plotting the results, guessing a nonlinear model, and fitting the constants. The mean squared error for the predicted x transition point as a function of s and prec is about 1. The model looks solid enough to me …
=> improve upper incomplete gamma algorithm selection for nonnegative real s and z

acb.h, acb/csc_pi.c, acb/gamma.c, acb/test/t-csc_pi.c, arb.h, arb/csc_pi.c, arb/gamma.c, arb/test/t-csc_pi.c, doc/source/acb.rst, doc/source/arb.rst
I was looking in the gamma.c files to try to improve the upper incomplete gamma function and I found a couple todo lines requesting `csc_pi`.
=> add csc_pi for arb_t and acb_t types

acb_dirichlet.h, acb_dirichlet/platt_multieval.c, acb_dirichlet/platt_multieval_threaded.c, acb_dirichlet/test/t-platt_multieval_threaded.c, doc/source/acb_dirichlet.rst
Add a multithreaded version of a grid evaluation function for computing zeta zeros. It's based on Rudolph's code in https://github.com/fredrik-johansson/arb/issues/320 and on the threading ideas in the multithreaded matrix multiplication.
=> Platt multieval threaded

arb/cot_pi.c, arb/log_hypot.c, arb/sinc_pi.c, arb/tan_pi.c, arb/test/t-cot_pi.c, arb/test/t-log_hypot.c, arb/test/t-sinc.c, arb/test/t-sinc_pi.c, arb/test/t-tan_pi.c
With these changes, the functions mentioned in https://github.com/fredrik-johansson/arb/issues/306 now pay closer attention to infinite inputs. I didn't make all of the requested changes though. For example I still have tan_pi(1/2) = NaN because the limit is +inf or -inf depending on whether it's approached from the positive or negative direction. I don't know if that's how it should work or not.
=> Treat infinite inputs more carefully.

acb_dft.h, acb_dft/rad2.c, acb_dft/rad2_threaded.c, acb_dft/test/t-dft.c
This PR adds radix 2 dft multi-threading. It's slower for small vectors and faster for large vectors, so I've hardcoded a threshold where multi-threading will only be used implicitly when the vector length is greater than 2^9.
The dft consists of three nested loops. The outer serial loop does log2(n) iterations and is not parallelized at all. The two nested inner loops consist of 2^a and 2^b iterations respectively for each combination of a and b where a+b+1= log2(n), and they can be jointly parallelized to spread the work evenly among threads. I used the threaded matrix multiplication code as the example of how to do multi-threading with the pthreads library.
I see that @pascalmolin wrote a lot of the dft stuff in arb, maybe if I did something dumb in this PR he would notice.
Here's some …
=> add radix2 dft multi-threading

Makefile.in, configure
closes https://github.com/fredrik-johansson/arb/issues/321
The arb configure and Makefile.in files are derived from flint which has an [interfaces](https://github.com/wbhart/flint2/tree/trunk/interfaces) directory containing [NTL-interace.cpp](https://github.com/wbhart/flint2/blob/trunk/interfaces/NTL-interface.cpp) and its tests and docs. But arb doesn't have those things so this PR removes all references to them in its build scrips.
=> do not try to build ntl interface

acb_dirichlet.h, acb_dirichlet/platt_hardy_z_zeros.c, acb_dirichlet/platt_local_hardy_z_zeros.c, acb_dirichlet/platt_multieval.c, acb_dirichlet/platt_zeta_zeros.c, acb_dirichlet/test/t-platt_hardy_z_zeros.c, acb_dirichlet/test/t-platt_zeta_zeros.c, doc/source/acb_dirichlet.rst
Automatic parameter selection at low height was changed so that testing the new functions is not prohibitively slow. The threshold at which A=8 changes to A=16 was moved slightly.
=> hardy z zeros and zeta zeros wrapper functions with tuning changes

doc/source/arb.rst
This would have saved me digging up the source code.
=> Rounding direction added to arb.h documentation

acb_mat.h, acb_mat/approx_mul.c, acb_mat/mul_classical.c, acb_mat/mul_threaded.c, arb_mat.h, arb_mat/approx_mul.c, arb_mat/mul_block.c, arb_mat/mul_classical.c, arb_mat/mul_threaded.c
I noticed that most `mat_mul`-functions (with `mat_mul_entrywise` being an exception) do not work properly for aliased window-matrices. The reason for this is that `mat_swap` destroys the entanglement of the window matrices with their parent matrix.
This can be seen with the following code-snippet:
```
void arb_mat_mul_aliased_window_test(){
arb_mat_t A, B, A_window;
arb_mat_init(A, 2, 2);
arb_mat_init(B, 2, 2);
arb_mat_window_init(A_window, A, 0, 0, 2, 2);
arb_mat_one(A);
arb_mat_ones(B);
printf("Before multiplication: \n");
printf("A: \n");
arb_mat_printd(A, 10);
printf("A_window: \n");
arb_mat_printd(A_window, 10);
arb_mat_mul_classical(A_window, B, A_window, 53);
printf("After multiplication: \n");
printf("A: \n");
arb_mat_printd(A, 10);
printf("A_window: \n"); …
```
=> Fixed bug for aliased mat_mul of window matrices

acb_poly.h, acb_poly/graeffe_transform.c, acb_poly/test/t-graeffe_transform.c, arb_poly.h, arb_poly/graeffe_transform.c, arb_poly/test/t-graeffe_transform.c, doc/source/acb_poly.rst, doc/source/arb_poly.rst
If `P` is a polynomial (over an arbitrary ring R), then its Graeffe transform `G` is defined through the equation `G(x^2) = P(x)P(-x)` (up to an overall sign, which is determined by the degree of P).
If L//R is the splitting field of P, then it is easy to see, that G also decomposes over L, and its roots are exactly the squares of the roots of P. In particular, in some cases the roots of G might be real even though those of P were not.
Due to the symmetry of G, we see that in computing `P(x)P(-x)`, half the terms will vanish (namely precisely the odd terms). This wastes time and memory. Instead, this implementation uses the definition in [\[Diouf, Sec. 1.2\]](https://tel.archives-ouvertes.fr/tel-00151313/document), which yields a significant performance benefit for the reason mentioned …
=> Implement Graeffe Transform for arb_poly and acb_poly

acb_poly/graeffe_transform.c, acb_poly/test/t-graeffe_transform.c, arb_poly/graeffe_transform.c, arb_poly/test/t-graeffe_transform.c
In the case of a constant polynomial (meaning degree 0 or length 1), the Graeffe Transform as implemented in #374 simply returned the input polynomial. That is incorrect; it should return the input polynomial squared.
This PR fixes that, and adapts the test code to cover non-monic polynomials.
=> Fix Graeffe transform for constant polynomials

acb.h, doc/source/acb.rst
Also add acb_add_error_arf to the documentation.
This is nice to have when developing libraries where error-bounds need to be calculated using arbs (for example if they involve special functions like upper incomplete gamma functions etc.).
Let me know if anything can be improved, or if tests are needed.
=> Add acb_add_error_arb

doc/source/acb.rst, doc/source/arb.rst
I assume that `arb_expm1` does not compute incorrectly for larger `x`, and I therefore copied the documentation from `acb_expm1`.
I also took the liberty of changing some symbols that I suspect where copy-pasta from somewhere.
=> Minor documentation changes

doc/source/acb_dirichlet.rst, doc/source/acb_poly.rst, doc/source/arb_poly.rst, doc/source/bool_mat.rst
I noticed that the function `acb_dirichler_hurwitz_precomp_choose_param`
had misspelled `dirichlet` in the documentation (not the code). This
corrects that, and a few other less important typos at the same time.
=> Correct typos in documentation.

configure
ARB does not build correctly in `MINGW64`. `-std=c99` needs to be added to `CFLAGS` in `configure` script. Also copied some more logic related to auto detection of `OS` and `ARCH` from https://github.com/fredrik-johansson/flint2/blob/trunk/configure
=> Fixing MINGW64 build

acb_dirichlet.h, acb_dirichlet/platt_lemma_B1.c, acb_dirichlet/platt_local_hardy_z_zeros.c, acb_dirichlet/platt_multieval.c, acb_dirichlet/platt_multieval_threaded.c, acb_dirichlet/test/t-platt_local_hardy_z_zeros.c, acb_dirichlet/test/t-platt_multieval.c, acb_dirichlet/test/t-platt_multieval_threaded.c, doc/source/acb_dirichlet.rst, doc/source/examples.rst, examples/zeta_zeros.c
closes https://github.com/fredrik-johansson/arb/issues/349
I think the old code would overflow at large heights if slong is 32 bits.
=> use fmpz instead of slong for the J parameter of windowed zeta zeros

arb.h, arb/nonnegative_abs.c, arb/test/t-nonnegative_abs.c, doc/source/arb.rst
Note the following behaviour. Taking the "nonnegative abs" of `[0 \pm 1]`:
```
arb_t t;
arb_init(t);
arf_zero(arb_midref(t));
mag_one(arb_radref(t));
arb_nonnegative_abs(t, t);
```
you don't get the exact interval `[0.5 \pm 0.5]`, but instead the centre and radius are one ulp (of a `mag_t`) greater than that. That ulp is introduced in `arf_get_mag`. I'm not sure there is an obvious workaround for that. (The example I ran into started with `[0 \pm 0.25]`, but I think `[0 \pm 1]` should work the same.)
Note furthermore that the "whole real line" object can be returned by this function, which still contains negative numbers. So the result does *not* always satisfy `arb_is_nonnegative`. Neither does NaN, of course. I think those are the only two cases.
=> Issue 441: create arb_nonnegative_abs.

arb/pow.c, arb/test/t-pow.c, doc/source/arb.rst
I rearranged the existing code for negative exact large integers y a little; explanation follows. Of course I'm happy to undo this if you prefer.
This code interacts with the new branch in a slightly complicated way: if `y` is an exact *small* integer (or half integer), we want to keep using the existing code that calls `arb_pow_fmpz_binexp`, so the new code needs to come *after* that test. However, if `y` is an exact *big* negative integer, then the current code negates `x` if its midpoint is negative, which would screw up the new code if we inserted it after the block testing for `arb_is_exact(y) && !arf_is_special(arb_midref(x))`, keeping the latter unchanged. I assume we want to keep testing that condition only once (as in the original code), so instead of immediately negating `x` and …
=> Fix arb_pow for x just barely containing 0, y>0.
